"use client"

import { useEffect, useRef, useState, ReactNode } from "react"

type Tab = "shell" | "config" | "log"

interface Line {
  tone: "prompt" | "out" | "ok" | "comment" | "plain"
  text: string
}

const SHELL_LINES: Line[] = [
  { tone: "comment", text: "# scaffold a new agent and deploy it" },
  { tone: "prompt", text: "$ 8004 init deep-researcher" },
  { tone: "out", text: "  → scaffolding project structure" },
  { tone: "out", text: "  → generating agent.toml" },
  { tone: "out", text: "  → creating Circle wallet" },
  { tone: "prompt", text: "$ 8004 deploy --network fuji" },
  { tone: "out", text: "  → verifying endpoint" },
  { tone: "out", text: "  → minting identity NFT (sponsored)" },
  { tone: "out", text: "  → listing to marketplace" },
  { tone: "ok", text: "✓ agent live · 8004.network/deep-researcher" },
]

const CONFIG_LINES: ReactNode[] = [
  <><span className="t-comment"># agent.toml — generated by `8004 init`</span></>,
  <><span className="t-keyword">[agent]</span></>,
  <><span className="t-keyword">name</span>      = <span className="t-string">&quot;deep-researcher&quot;</span></>,
  <><span className="t-keyword">category</span>  = <span className="t-string">&quot;research&quot;</span></>,
  <><span className="t-keyword">endpoint</span>  = <span className="t-string">&quot;https://api.helix.dev/agent&quot;</span></>,
  <><span className="t-keyword">owner</span>     = <span className="t-string">&quot;0x44a…f1&quot;</span></>,
  <>&nbsp;</>,
  <><span className="t-keyword">[pricing]</span></>,
  <><span className="t-keyword">per_call</span>   = <span className="t-number">0.05</span></>,
  <><span className="t-keyword">free_trial</span> = <span className="t-number">2</span></>,
  <><span className="t-keyword">currency</span>   = <span className="t-string">&quot;USDC&quot;</span></>,
  <>&nbsp;</>,
  <><span className="t-keyword">[networks]</span></>,
  <><span className="t-keyword">enabled</span> = [<span className="t-string">&quot;fuji&quot;</span>, <span className="t-string">&quot;base&quot;</span>, <span className="t-string">&quot;arbitrum&quot;</span>]</>,
]

const LOG_LINES: ReactNode[] = [
  <><span className="t-comment">// response.log · job 9921_Q</span></>,
  <><span className="t-keyword">{"{"}</span></>,
  <>  <span className="t-fn">&quot;status&quot;</span>   : <span className="t-ok">&quot;success&quot;</span>,</>,
  <>  <span className="t-fn">&quot;latency&quot;</span>  : <span className="t-string">&quot;1.24s&quot;</span>,</>,
  <>  <span className="t-fn">&quot;cost&quot;</span>     : <span className="t-string">&quot;$0.047&quot;</span>,</>,
  <>  <span className="t-fn">&quot;tokens&quot;</span>   : <span className="t-number">4128</span>,</>,
  <>  <span className="t-fn">&quot;output&quot;</span>   : <span className="t-keyword">{"{"}</span></>,
  <>    <span className="t-fn">&quot;summary&quot;</span>  : <span className="t-string">&quot;competitor landscape synthesized&quot;</span>,</>,
  <>    <span className="t-fn">&quot;citations&quot;</span>: <span className="t-number">12</span></>,
  <>  <span className="t-keyword">{"}"}</span>,</>,
  <>  <span className="t-fn">&quot;rating&quot;</span>   : <span className="t-number">4.9</span>,</>,
  <>  <span className="t-fn">&quot;paid_to&quot;</span>  : <span className="t-string">&quot;0x44a…f1&quot;</span></>,
  <><span className="t-keyword">{"}"}</span></>,
]

function toneClass(tone: Line["tone"]) {
  switch (tone) {
    case "prompt": return "t-prompt"
    case "out":    return "t-out"
    case "ok":     return "t-ok"
    case "comment":return "t-comment"
    default:       return "t-out"
  }
}

export function CodeEditor() {
  const [tab, setTab] = useState<Tab>("shell")
  const [typedChars, setTypedChars] = useState(0)
  const [started, setStarted] = useState(false)
  const ref = useRef<HTMLDivElement>(null)
  const fullShell = SHELL_LINES.map(l => l.text).join("\n")

  useEffect(() => {
    const el = ref.current
    if (!el) return
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches
    if (reduced) {
      setStarted(true)
      setTypedChars(fullShell.length)
      return
    }
    const obs = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && !started) {
          setStarted(true)
        }
      },
      { threshold: 0.3 }
    )
    obs.observe(el)
    return () => obs.disconnect()
  }, [started, fullShell.length])

  useEffect(() => {
    if (!started) return
    if (typedChars >= fullShell.length) return
    const delay = 8 + Math.floor(Math.random() * 18)
    const t = setTimeout(() => setTypedChars((n) => n + 1), delay)
    return () => clearTimeout(t)
  }, [started, typedChars, fullShell.length])

  // Render shell with partial typing
  function renderShell() {
    const typed = fullShell.slice(0, typedChars)
    const typedLines = typed.split("\n")
    const done = typedChars >= fullShell.length
    return (
      <>
        {SHELL_LINES.map((line, i) => {
          if (i > typedLines.length - 1) return null
          const textForThisLine = typedLines[i] ?? ""
          const isLast = i === typedLines.length - 1
          return (
            <span key={i} className={`ln ${toneClass(line.tone)}`}>
              {textForThisLine}
              {isLast && !done && <span className="code-editor__cursor" />}
              {isLast && done && i === SHELL_LINES.length - 1 && (
                <span className="code-editor__cursor" />
              )}
            </span>
          )
        })}
      </>
    )
  }

  const visibleLineCount =
    tab === "shell"
      ? Math.max(1, Math.min(SHELL_LINES.length, (fullShell.slice(0, typedChars).split("\n").length)))
      : tab === "config"
        ? CONFIG_LINES.length
        : LOG_LINES.length

  return (
    <div ref={ref} className="code-editor">
      <div className="code-editor__chrome">
        <div className="code-editor__lights">
          <span /><span /><span />
        </div>
        <div className="code-editor__tabs">
          <button
            className="code-editor__tab"
            data-active={tab === "shell"}
            onClick={() => setTab("shell")}
            type="button"
          >
            shell
          </button>
          <button
            className="code-editor__tab"
            data-active={tab === "config"}
            onClick={() => setTab("config")}
            type="button"
          >
            agent.toml
          </button>
          <button
            className="code-editor__tab"
            data-active={tab === "log"}
            onClick={() => setTab("log")}
            type="button"
          >
            response.log
          </button>
        </div>
      </div>

      <div className="code-editor__body">
        <div className="code-editor__gutter">
          {Array.from({ length: visibleLineCount }).map((_, i) => (
            <span key={i}>{String(i + 1).padStart(2, "0")}</span>
          ))}
        </div>
        <div className="code-editor__code">
          {tab === "shell" && renderShell()}
          {tab === "config" &&
            CONFIG_LINES.map((node, i) => (
              <span key={i} className="ln">{node}</span>
            ))}
          {tab === "log" &&
            LOG_LINES.map((node, i) => (
              <span key={i} className="ln">{node}</span>
            ))}
        </div>
      </div>

      <div className="code-editor__statusbar">
        <span>READY</span>
        <span>UTF-8</span>
        <span>LF</span>
        <span>{tab === "shell" ? "SHELL" : tab === "config" ? "TOML" : "JSON"}</span>
        <span style={{ marginLeft: "auto" }}>8004 · V1.14</span>
      </div>
    </div>
  )
}
